spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/discussion_db
    username: ${LOCAL_DB_USER:postgres}
    password: ${LOCAL_DB_PASSWORD:postgres}
